language: python
python:
  - "3.5" 
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  - echo "feature1,feature2,feature3;1,2,3" > test.csv
  - pytest -v
after_success:
  - pytest --cov=./
  - codecov 
